name: OWASP ZAP Scan

on:
  push:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'https://ananth211.github.io/simple-webpage/'
